# `.air.toml`

# プロジェクトのルートディレクトリ
root = "."

# 一時ビルドファイルの格納場所
tmp_dir = "tmp"

[build]
  # `go build` の対象を `cmd/hello` に変更
  cmd = "go build -o tmp/main ./cmd/hello"
  bin = "tmp/main"
  delay = 1000
  stop_on_error = true

[watcher]
  # 監視するファイルの指定
  includes = ["*.go"]
  excludes = ["tmp/*", "vendor/*"]
