version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "2345:2345"
    command: ["air"]
    depends_on:
      db:
        condition: service_healthy  # db の healthcheck 成功後に起動
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Docker の内部ボリューム（docker volume ls で確認可能）
      # - ./mysql_data:/var/lib/mysql # プロジェクトディレクトリの mysql_data/ フォルダに保存
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
