# 1. 開発用の Golang コンテナ
FROM golang:1.23 AS dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# 開発用ツールをインストール
RUN go install github.com/air-verse/air@latest \
    && go install github.com/go-delve/delve/cmd/dlv@latest

COPY . .

CMD ["air"]
